services:
  alertmanager:
    command:
      - --config.file=/etc/alertmanager/alertmanager.slack.yml
      - --storage.path=/alertmanager
    volumes:
      - ./observability/alertmanager/alertmanager.slack.yml:/etc/alertmanager/alertmanager.slack.yml:ro
      - ./.secrets/slack_webhook_url:/run/secrets/slack_webhook_url:ro
      - alertmanager-data:/alertmanager
